# Site settings
title: Fake Data
email: your-email@domain.com
description: "Fake it 'til they make the API"
baseurl: "/fakedata/"
url: "http://ineedyourbrain.github.io/fakedata/"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
