# Site settings
title: DataIpsum
email: your-email@domain.com
description: "Fake it 'til they make the API"
baseurl: ""
url: "http://ineedyourbrain.github.io/fakedata/"
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
permalink: pretty
